server {
  listen 80;
  
  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/api/;
  }
  
  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8000/admin/;
  }

  # Отдаем статические файлы фронтенда
  location /static/ {
    alias /static/;
  }

  # Все остальные запросы отдаем index.html
  location / {
    root /static;
    index index.html;
    try_files $uri $uri/ /index.html;
  }
}